services:
#    app_app.example:
#        class: App\AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    corredorrepository:
         alias: corredorrepository.inmemory
    corredorrepository.inmemory:
         class: App\CorredoresRiojaInfrastructure\InMemoryRepository\InMemoryCorredorRepository
         public: false
         
    carrerarepository:
         alias: carrerarepository.inmemory
    carrerarepository.inmemory:
         class: App\CorredoresRiojaInfrastructure\InMemoryRepository\InMemoryCarreraRepository
         public: false
           
    organizacionrepository:
         alias: organizacionrepository.inmemory
    organizacionrepository.inmemory:
         class: App\CorredoresRiojaInfrastructure\InMemoryRepository\InMemoryOrganizacionRepository
         public: false
         
    participanterepository:
         alias: participanterepository.inmemory
         
    participanterepository.inmemory:
         class: App\CorredoresRiojaInfrastructure\InMemoryRepository\InMemoryParticipanteRepository
         public: false
         
    corredores_user_provider:
        class : App\CorredoresRiojaDomain\Security\CorredorUserProvider
        arguments: ["@corredorrepository"]
